### ISSUE TITLE
.NET 5 Support

### ISSUE THREAD

**Issue by AshleighAdams** [EvergineTeam/WebGL.NET#15]
Is there anyway to run this on .NET 5?

**Comment by MarcosCobena** [comment]
To be honest, I have still not tried that; however, I think it should work. WebGL.NET is just a small interop layer with the JavaScript API.

NuGets currently depend on former Mono Wasm ones but, it should be easy to move to .NET 5.

**Comment by AshleighAdams** [comment]
@MarcosCobena Ah, do you mean WebAssembly.Bindings? I did look at finding the equivalent for dotnet 5, but couldn't see any publicly exposed replacements.

**Comment by MarcosCobena** [comment]
This looks as a candidate :-)

https://www.nuget.org/packages/Microsoft.JSInterop.WebAssembly/

**Comment by AshleighAdams** [comment]
@MarcosCobena I was reading the update you left on the readme, about how Wave uses Emscripten EGL for WebGL now. Is there a barebones WebGL reference project using WaveEngine.OpenGL.NET you can share at all? I'm struggling to see how you'd set up the context to render on a canvas with it without WaveEngine and/or Mono's bindings libs.

Thanks

**Comment by MarcosCobena** [comment]
Afaik, there is no source code publicly available with the latest changes in Wave; however, this game already uses such and, with F12 ;-), you can gather how it is all done underneath:

https://innovation.microsoft.com/en-us/exploring-project-paidia > Click on Try the interactive demonstration

**Comment by AshleighAdams** [comment]
To anyone that stumbles on this thread, this is easy doable now in .NET 6 without the use of this library.

I have a WebGL sample here, and it's trivial to switch it to use WaveEngine.Bindings.OpenGLES: https://github.com/AshleighAdams/dotnet6-webgl-sample

Closing this issue.
